### ISSUE TITLE
Compile scripts need to be fixed & pymatgen version

### ISSUE THREAD

**Issue by adenchfi** [comscope/ComDMFT#3]
Hi,

I'm coming back to try ComDMFT & compiling from source from the master branch. 
-- The Makefiles are a bit out of whack however. I needed to change the Makefiles in ComCTQMC because labels like cxx_lmpi were hardcoded, rather than inheriting from the master makefile.
-- I'm not sure if it's syntax changes or what, but at least the flapwmbpy_ini.py script isn't working. For example running the flapwmbpt_ini.py on Na.cif still yields the same error in the other issue I opened years ago. The sp.kpath yields None. 

Will open more issues as I try using the code, these are just the ones I found as I've spent an hour getting it installed.

**Comment by adenchfi** [comment]
Ah, another issue:
-- Running rspflapw.exe on the /dft/ example with the .ini file already generated (I had to rename comdmft.ini to ini), I get:
mellow@pop-os:~/sys76_laptop/grad_school/Research/ElPh_DMFT/comsuite/ComDMFT/2021School_tutorials_input/dft$ ./rspflapw.exe 
         'method':'dft',
 --------------------------^^^^^^ 
 ERROR: reading beyond the end of the line

The same thing happens for the /tutorials/dft/NiO/ example. The llscript in that directory refers to comdmft.py, but running that yields the same python error with the crystal structure:

`Traceback (most recent call last):
  File "/home/mellow/sys76_laptop/grad_school/Research/ElPh_DMFT/comsuite/ComDMFT/2021School_tutorials_input/dft/../../bin/comdmft.py", line 3801, in <module>
    run_flapwmbpt(control)
  File "/home/mellow/sys76_laptop/grad_school/Research/ElPh_DMFT/comsuite/ComDMFT/2021School_tutorials_input/dft/../../bin/comdmft.py", line 3527, in run_flapwmbpt
    flapwmbpt_ini.main()
  File "/home/mellow/sys76_laptop/grad_school/Research/ElPh_DMFT/comsuite/ComDMFT/bin/flapwmbpt_ini.py", line 1741, in main
    xtalstr  = fm.crystalstructure(str_in)
  File "/home/mellow/sys76_laptop/grad_school/Research/ElPh_DMFT/comsuite/ComDMFT/bin/flapwmbpt_input/crystalstructure.py", line 109, in __init__
    for labellist in sp.kpath["path"]:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by sandimas** [comment]
pymatgen changed their nomenclature. I fixed this issue by replacing line 104 of bin/flapwmbpt_input/crystalstructure.py with

        sp = mg.symmetry.bandstructure.HighSymmKpath(self.str, path_type='setyawan_curtarolo')
